docs(api/endpoints): Generated swagger.yml with some endpoint mockups
Capstone-user-app/user-api pull request #1
Opened 2022-09-22 03:10 UTC by domingo2000

## Description
- Added a basic swagger.yml OpenAPI 3 schema to document some mockup endpoints that could be implemented in the API
- Added some UML diagram (Sequence and Component) for documentation

### Motivation
Model the new clients API with all the responses, flows, and possible complications.
Why i want to merge these changes?
To reflect the current modeling in the main branch

What are the changes?
swagger.yml file
sequence diagram png
component diagram png
## Checklist:

- [X] This PR sets the target branch to main (or the correct target environment)
- [X] This PR has latest changes from main branch (git merge origin/dev)
- [X] This PR was self-reviewed (Check your changes before asking for review)
- [X] This PR was documented (particularly in hard-to-understand areas)
- [X] This PR updates the technical documentation (under /docs)
- [ ] This PR requires new deployment configurations
- [ ] This PR has migrations pointing to the latest revision in target branch
- [X] This PR has test cases for every change made
- [X] This PR passed all previous tests

2022-09-22 12:48 UTC, imant1 requested changes
En `docs/Flow Diagram Clients API.drawio.png`, en el último diagrama (abajo a la derecha) en en la nota debería decir "Note: non-existent sale" (ahora mismo sale "Forbidden SHOW")

2022-09-22 13:16 UTC, imant1 commented
Hay que tener en consideración que Javier dijo que estaban trabajando en una implementación de auth0 que debería estar lista pronto (hay q definir qué es pronto). Hay que ver como usariamos esa implementación, por ejemplo si es que el token de auth0 se pide directo desde front o el front solo se comunica con el back q a su vez llama a la API de auth0

2022-09-22 14:01 UTC, domingo2000 commented
1. Arreglo altiro el diagrama tienes razón.
2. Yo feliz usaría auth0 para el manejo de clientes, pero si ellos lo están transicionando y tenemos que esperarlos igual sería muy lento, podríamos hacer un flujo de usuarios temporal interno. Si nosotros configuramos el auth0 no tengo ningún problema, de hecho preferiría usar auth0 en vez de implementarlo nosotros para no tener que hacer flujos de cambios de contraseña, refresh tokens, etc etc.

2022-09-22 16:17 UTC, R0W5tortion commented
1. En el diagrama creo que cambiaste la NOTE equivocada, el Forbidden debería tirar 403 y el Not Found debería tirar 404
2. En el swagger en la entidad de Sale hay un atributo saleSale, es así o querías poner saleId?

2022-09-23 15:06 UTC, domingo2000 commented
> 1. En el diagrama creo que cambiaste la NOTE equivocada, el Forbidden debería tirar 403 y el Not Found debería tirar 404
> 2. En el swagger en la entidad de Sale hay un atributo saleSale, es así o querías poner saleId?

Tenías razón, arreglado, cambié tambien las rutas de las API de `/sales` pues el `/clients` en realidad queda de más si nos entra un token de cliente en la request. La idea es que ese swagger.yml quede de ejemplo para documentación de los otros endpoints que hagamos

2022-09-23 21:33 UTC, ignaciomansuy approved these changes

2022-09-23 21:33 UTC, merged